steps:
- name: 'gcr.io/cloud-builders/docker'
  args : ['build','-t', 'gcr.io/symbolic-bit-249313/nodeserver','.']
- name: 'gcr.io/cloud-builders/gcloud'
  args : ['deploy','app']
  timeout: '1600s'
  
images: ['gcr.io/symbolic-bit-249313/nodeserver']
timeout: '2000s'
